// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhcVM-u7g_oQBJZRQoldXGCTfBzGmSEA',
    appId: '1:341070514716:android:9daa42435627ae59bdadd9',
    messagingSenderId: '341070514716',
    projectId: 'app-gestion-inventario',
    storageBucket: 'app-gestion-inventario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCelAw6nQjzqVcVzG6o7FdwzaTgFIQPMMI',
    appId: '1:341070514716:ios:57d9868e0d0717a9bdadd9',
    messagingSenderId: '341070514716',
    projectId: 'app-gestion-inventario',
    storageBucket: 'app-gestion-inventario.firebasestorage.app',
    androidClientId: '341070514716-c3vmkdiob3sluj4uptm3ojs6s5edhsng.apps.googleusercontent.com',
    iosClientId: '341070514716-u80429vhk691mmspmklugn54ccq806hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionInventario',
  );
}
